on: 
  workflow_dispatch:
    inputs:
      some_input:
        description:'説明'
        required:　true
        default:　'hogehoge'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  on_pr_workflow_dispatch:
    runs-on: ubuntu-latest

    steps: 
      - name: Chackout
        uses: actions/checkout@v2

      - name: Env set
        env:
          SOME_STRING: hoge
        run: echo $SOME_STRING

      - name: Without env
        run: echo $SOME_STRING
