on: 
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  on_pr_workflow_dispatch:
    runs-on: ubuntu-latest

    steps: 
      - name: Chackout
        uses: actions/checkout@v2

      - name: Check env values
        env:
          BRANCH_NAME: ${{ (github.event_name == 'pull_request' && '$GITHUB_HEAD_REF') || $GITHUB_REF_NAME }}
        run: |
          echo "GITHUB_REF_NAME"
          echo $GITHUB_REF_NAME
          echo "GITHUB_HEAD_REF"
          echo $GITHUB_HEAD_REF
          echo "これでどう"
          echo $BRANCH_NAME

