on: 
  push:
    branches:
      - main

jobs:
  on_push_job:
    runs-on: ubuntu-latest

    steps: 
      - name: Chackout
        uses: actions/checkout@v2

      - name: Check env values
        run: |
          echo $GITHUB_REF_NAME
          echo $GITHUB_HEAD_REF
