on: 
  workflow_dispatch:
    inputs:
      some_input:
        description: '説明'
        required: true
        default: 'hogehoge'

jobs:
  on_pr_workflow_dispatch:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: ""
