name: workflow_dispatch_sample

on: workflow_dispatch

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Run
        run: |
          echo $(((false || false) && 1 || 2))
          echo ${{ false }}
          echo ${{(false || false) && 1 || 2 }}
