name: workflow_dispatch_sample2

on: 
  workflow_dispatch:

jobs: 
  workflow_dispatch_sample2:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Set envs
        run: |
          echo "MY_ENV=huga" >> "$GITHUB_ENV"
      - name: Run
        run: |
          echo $MY_ENV
