name: workflow_dispatch_sample

on: 
  workflow_dispatch:
    inputs:
      flag:
        description: 'flag'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Run
        run: |
          echo $(((false || false) && 1 || 2)) #1
          echo ${{ false }} #false
          echo ${{(false || false) && 1 || 2 }} #2
          echo ${{(false || github.event.inputs.flag) && 1 || 2 }} #1
          echo ${{ false || github.event.inputs.flag }}
          
