name: workflow_dispatch_sample

on: workflow_dispatch

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Chackout
        uses: actions/checkout@v2

      - name: Run
        run: |
          if [ "$github.event_name" = "workflow_dispatch" ]; then
            echo "1"
          fi
          echo "2"
      - name: Run next
        run: |
          echo "3"
