name: workflow_dispatch_sample

on: workflow_dispatch

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Chackout
        uses: actions/checkout@v2

      - name: Exit 0
        run: |
          echo "started"
          exit 0

      - name: Succeeded process
        run: echo "succeeded"

      - name: Failed process
        if: failure()
        run: echo "failed"
