name: workflow_dispatch_sample

on: 
  workflow_dispatch:
    inputs:
      flag:
        description: 'flag'
        required: true
        type: boolean

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Run
        run: |
          echo ${{ false && 1 || 2 }}
          echo ${{ github.event.inputs.flag == 'true' && 1 || 2 }}
          echo ${{ github.event.inputs.flag && 1 || 2 }}
          echo $(((false || false) && 1 || 2)) #1
          echo ${{ false }} #false
          echo ${{(false || false) && 1 || 2 }} #2
          echo ${{(false || github.event.inputs.flag) && 1 || 2 }} #1
          echo ${{　false || github.event.inputs.flag && 1 || 2 }} #1
          echo ${{ false || github.event.inputs.flag }}
          echo ${{ (false || github.event.inputs.flag) }}
          
