name: workflow_dispatch_sample

on: workflow_dispatch

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Chackout
        uses: actions/checkout@v2

      - name: Run
        run: |
          TODAY=`date "+%Y/%m/%d"`
          CD=`git log -1 --date=format:"%Y/%m/%d" --format="%ad"`
          if [ "＄TODAY" = "$CD" ]; then
            echo "1"
          else
            echo $TODAY
            echo $CD
          fi
