name: workflow_dispatch_sample

on: workflow_dispatch

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Run
        run: |
          echo $(((false || false) && 1 || 2)) #1
          echo ${{ false }} #false
          echo ${{(false || false) && 1 || 2 }} #2
          echo ${{(false || contains(github.event.pull_request.labels.*.name, 'Flag')) && 1 || 2 }}
          
