name: workflow_dispatch_sample

on: 
  workflow_dispatch:
    inputs:
      flag:
        description: 'flag'
        required: true
        type: boolean

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest
    env:
      MY_ENV: >- 
        ${{
          github.event.inputs.flag == 'true'
            && ''
            || '-Dorg.gradle.jvmargs="-XmxXXXm -XX:MaxMetaspaceSize=XXXm -Dkotlin.daemon.jvm.options=-XmxXXXm"'
        }}

    steps: 
      - name: Run
        run: |
          echo $MY_ENV
