name: workflow_dispatch_sample

on: workflow_dispatch

jobs: 
  workflow_dispatch_sample:
    runs-on: ubuntu-latest

    steps: 
      - name: Chackout
        uses: actions/checkout@v2

      - name: Run
        run: |
          echo "${{ github.event.action }}"
          echo `"${{ github.event.action }}" = "workflow_dispatch"`
